### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by SmokingWalrus** [litecoin-project/litecore-node#26]
```
sam@DESKTOP-O7HJNUL:~/litecoin-0.13.2/bin$ sudo npm install -g litecore-node
[sudo] password for sam:
npm WARN deprecated mkdirp@0.5.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3

> litecore-node@3.1.11 preinstall /usr/local/lib/node_modules/litecore-node
> ./scripts/download

Downloading litecoin: https://github.com/litecoin-project/litecore-litecoin/releases/download/v0.13.2.1-litecore-rc2/litecoin-0.13.2-x86_64-linux-gnu.tar.gz
./scripts/download: line 44: litecoin-0.13.2-x86_64-linux-gnu.tar.gz: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! litecore-node@3.1.11 preinstall: `./scripts/download`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the litecore-node@3.1.11 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-06T16_29_20_559Z-debug.log
sam@DESKTOP-O7HJNUL:~/litecoin-0.13.2/bin$
```

Log says:
```
6256 silly preinstall for-in@1.0.2
6257 info lifecycle for-in@1.0.2~preinstall: for-in@1.0.2
6258 silly preinstall flagged-respawn@1.0.1
6259 info lifecycle flagged-respawn@1.0.1~preinstall: flagged-respawn@1.0.1
6260 silly preinstall extend@3.0.2
6261 info lifecycle extend@3.0.2~preinstall: extend@3.0.2
6262 silly preinstall expand-template@1.1.1
6263 info lifecycle expand-template@1.1.1~preinstall: expand-template@1.1.1
6264 silly preinstall etag@1.8.1
6265 info lifecycle etag@1.8.1~preinstall: etag@1.8.1
6266 silly preinstall escape-html@1.0.3
6267 info lifecycle escape-html@1.0.3~preinstall: escape-html@1.0.3
6268 silly preinstall negotiator@0.6.1
6269 info lifecycle negotiator@0.6.1~preinstall: negotiator@0.6.1
6270 silly preinstall debug@2.3.3
6271 info lifecycle debug@2.3.3~preinstall: debug@2.3.3
6272 verbose lifecycle litecore-node@3.1.11~preinstall: PATH: /usr/share/npm/node_modules/npm-lifecycl>6273 verbose lifecycle litecore-node@3.1.11~preinstall: CWD: /usr/local/lib/node_modules/litecore-node
6274 silly lifecycle litecore-node@3.1.11~preinstall: Args: [ '-c', './scripts/download' ]
6275 silly lifecycle litecore-node@3.1.11~preinstall: Returned: code: 1  signal: null
6276 info lifecycle litecore-node@3.1.11~preinstall: Failed to exec preinstall script
6277 timing action:preinstall Completed in 601ms
6278 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node>6279 timing stage:rollbackFailedOptional Completed in 165ms
6280 timing stage:runTopLevelLifecycles Completed in 9656ms
6281 verbose stack Error: litecore-node@3.1.11 preinstall: `./scripts/download`
6281 verbose stack Exit status 1
6281 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js>6281 verbose stack     at EventEmitter.emit (events.js:198:13)
6281 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spaw>6281 verbose stack     at ChildProcess.emit (events.js:198:13)
6281 verbose stack     at maybeClose (internal/child_process.js:982:16)
6281 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
6282 verbose pkgid litecore-node@3.1.11
6283 verbose cwd /home/sam/litecoin-0.13.2/bin
6284 verbose Linux 5.4.72-microsoft-standard-WSL2
6285 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "litecore-node"
6286 verbose node v10.19.0
6287 verbose npm  v6.14.4
6288 error code ELIFECYCLE
6289 error errno 1
6290 error litecore-node@3.1.11 preinstall: `./scripts/download`
6290 error Exit status 1
6291 error Failed at the litecore-node@3.1.11 preinstall script.
6291 error This is probably not a problem with npm. There is likely additional logging output above.
6292 verbose exit [ 1, true ]
```

**Comment by SmokingWalrus** [comment]
Im trying to simply install it. Im running `npm install -g litecore-node` & `sudo npm install -g litecore-node`

Both are not working
