### ISSUE TITLE
Cannot read property '_scriptBuffer' of undefined at BlockController.getPoolInfo

### ISSUE THREAD

**Issue by HudsonProdigy** [litecoin-project/litecore-node#8]
The following error is crashing my node.

`[2018-01-17T19:24:21.192Z] error: uncaught exception: [TypeError: Cannot read property '_scriptBuffer' of undefined]
[2018-01-17T19:24:21.194Z] error: TypeError: Cannot read property '_scriptBuffer' of undefined
    at BlockController.getPoolInfo (/Users/coryhudson/TorontoCryptoClub/LiteCoinDevelopment/TestNetNode/node_modules/insight-api/lib/blocks.js:312:55)
    at /Users/coryhudson/TorontoCryptoClub/LiteCoinDevelopment/TestNetNode/node_modules/insight-api/lib/blocks.js:216:26
    at /Users/coryhudson/TorontoCryptoClub/LiteCoinDevelopment/TestNetNode/node_modules/litecore-node/node_modules/async/lib/async.js:676:51
    at /Users/coryhudson/TorontoCryptoClub/LiteCoinDevelopment/TestNetNode/node_modules/litecore-node/node_modules/async/lib/async.js:726:13
    at /Users/coryhudson/TorontoCryptoClub/LiteCoinDevelopment/TestNetNode/node_modules/litecore-node/node_modules/async/lib/async.js:52:16
    at /Users/coryhudson/TorontoCryptoClub/LiteCoinDevelopment/TestNetNode/node_modules/litecore-node/node_modules/async/lib/async.js:264:21
    at /Users/coryhudson/TorontoCryptoClub/LiteCoinDevelopment/TestNetNode/node_modules/litecore-node/node_modules/async/lib/async.js:44:16
    at /Users/coryhudson/TorontoCryptoClub/LiteCoinDevelopment/TestNetNode/node_modules/litecore-node/node_modules/async/lib/async.js:723:17
    at /Users/coryhudson/TorontoCryptoClub/LiteCoinDevelopment/TestNetNode/node_modules/litecore-node/node_modules/async/lib/async.js:167:37
    at /Users/coryhudson/TorontoCryptoClub/LiteCoinDevelopment/TestNetNode/node_modules/litecore-node/node_modules/async/lib/async.js:652:25
[2018-01-17T19:24:21.194Z] info: Beginning shutdown
[2018-01-17T19:24:21.195Z] info: Stopping insight-ui
[2018-01-17T19:24:21.195Z] info: Stopping insight-api
[2018-01-17T19:24:21.195Z] info: Stopping web
[2018-01-17T19:24:21.195Z] info: Stopping bitcoind
[2018-01-17T19:24:21.222Z] info: ::1 web socket subscribe: inv
[2018-01-17T19:24:21.232Z] info: ::1 web socket subscribe: sync
[2018-01-17T19:24:21.233Z] info: ::1 web socket subscribe: inv
[2018-01-17T19:24:21.233Z] info: ::1 web socket subscribe: sync
[2018-01-17T19:24:21.233Z] info: ::1 web socket subscribe: inv
[2018-01-17T19:24:21.233Z] info: ::1 web socket subscribe: sync
[2018-01-17T19:24:21.732Z] info: ::1 "GET /insight-api/currency" 200 43 640.209 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" 
Corys-iMac:TestNetNode coryhudson$ [2018-01-17T19:24:21.192Z] error: uncaught exception: [TypeError: Cannot read property '_scriptBuffer' of undefined]
-bash: [2018-01-17T19:24:21.192Z]: command not found
Corys-iMac:TestNetNode coryhudson$ [2018-01-17T19:24:21.194Z] error: TypeError: Cannot read property '_scriptBuffer' of undefined
-bash: [2018-01-17T19:24:21.194Z]: command not found
Corys-iMac:TestNetNode coryhudson$     at BlockController.getPoolInfo (/Users/coryhudson/TorontoCryptoClub/LiteCoinDevelopment/TestNetNode/node_modules/insight-api/lib/blocks.js:312:55)
-bash: syntax error near unexpected token `('
`
any help would be appreciated.

Cheers

**Comment by backcopy** [comment]
More information would be useful, your setup, in what context this error came up in, any more log files, etc.

You may wish to consider using a dedicated environment for your development, a type 1 virtualised VPS (KVM, XEN, etc) would be most ideal at minimum.

**Comment by Nerulls** [comment]
Im getting the same error althought it shuts down node the server gracefully.

It pops up only when someone is loads up the insight site
