### ISSUE TITLE
Node always crash - RangeError: index out of range

### ISSUE THREAD

**Issue by minzak** [litecoin-project/litecore-node#9]
Node always crash and restart. What is wrong?
listenonion=1 or 0 - not helps.

```
Mar  9 17:26:53 token-node-litecoin litecoin[24684]: [2018-03-09T17:26:53.911Z] info: Using config: /mnt/litecoin/node/litecore-node.json
Mar  9 17:26:53 token-node-litecoin litecoin[24684]: [2018-03-09T17:26:53.914Z] info: Using network: livenet
Mar  9 17:26:53 token-node-litecoin litecoin[24684]: [2018-03-09T17:26:53.915Z] info: Starting bitcoind
Mar  9 17:26:53 token-node-litecoin litecoin[24684]: [2018-03-09T17:26:53.927Z] info: Using bitcoin config file: /mnt/litecoin/node/data/bitcoin.conf
Mar  9 17:26:53 token-node-litecoin litecoin[24684]: [2018-03-09T17:26:53.931Z] info: Starting bitcoin process
Mar  9 17:26:58 token-node-litecoin litecoin[24684]: [2018-03-09T17:26:58.998Z] warn: Loading block index...
Mar  9 17:27:04 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:04.009Z] warn: Loading block index...
Mar  9 17:27:09 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:09.018Z] warn: Loading block index...
Mar  9 17:27:14 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:14.027Z] warn: Loading block index...
Mar  9 17:27:19 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:19.036Z] warn: Rewinding blocks...
Mar  9 17:27:24 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:24.044Z] warn: Rewinding blocks...
Mar  9 17:27:29 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:29.054Z] warn: Rewinding blocks...
Mar  9 17:27:34 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:34.066Z] warn: Rewinding blocks...
Mar  9 17:27:39 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:39.130Z] info: Bitcoin Height: 1382216 Percentage: 100.00
Mar  9 17:27:39 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:39.155Z] info: Bitcoin Daemon Ready
Mar  9 17:27:39 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:39.157Z] info: Starting web
Mar  9 17:27:39 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:39.210Z] info: Starting insight-api
Mar  9 17:27:39 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:39.211Z] info: Starting insight-ui
Mar  9 17:27:39 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:39.212Z] info: Bitcore Node ready
Mar  9 17:27:39 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:39.589Z] warn: ZMQ connection delay: tcp://127.0.0.1:29332
Mar  9 17:27:39 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:39.590Z] info: ZMQ connected to: tcp://127.0.0.1:29332
Mar  9 17:27:43 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:43.237Z] info: ::ffff:176.125.40.168 web socket subscribe: inv
Mar  9 17:27:43 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:43.284Z] info: ::ffff:176.125.40.168 web socket subscribe: sync
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:54.823Z] error: uncaught exception: [RangeError: index out of range]
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:54.830Z] error: RangeError: index out of range
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: at checkOffset (buffer.js:700:11)
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: at Buffer.readUInt32LE (buffer.js:762:5)
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: at BufferReader.readUInt32LE (/mnt/litecoin/node/node_modules/insight-api/node_modules/bitcore-lib/lib/encoding/bufferreader.js:81:22)
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: at Transaction.fromBufferReader (/mnt/litecoin/node/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/transaction.js:314:27)
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: at Transaction.fromBuffer (/mnt/litecoin/node/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/transaction.js:297:15)
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: at InsightAPI.transactionEventHandler (/mnt/litecoin/node/node_modules/insight-api/lib/index.js:267:30)
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: at emitOne (events.js:77:13)
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: at Bitcoin.emit (events.js:169:7)
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: at Bitcoin._zmqTransactionHandler (/mnt/litecoin/node/node_modules/litecore-node/lib/services/bitcoind.js:639:10)
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: at null.<anonymous> (/mnt/litecoin/node/node_modules/litecore-node/lib/services/bitcoind.js:713:12)
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:54.833Z] info: Beginning shutdown
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:54.834Z] info: Stopping insight-ui
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:54.836Z] info: Stopping insight-api
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:54.841Z] info: Stopping web
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:54.844Z] info: Stopping bitcoind
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:54.848Z] info: Bitcoin Height: 1382217 Percentage: 100.00
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: [2018-03-09T17:27:54.930Z] error: RPCError: Bitcoin JSON-RPC: Request Error: connect ECONNREFUSED 127.0.0.1:9332
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: at Bitcoin._wrapRPCError (/mnt/litecoin/node/node_modules/litecore-node/lib/services/bitcoind.js:449:13)
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: at /mnt/litecoin/node/node_modules/litecore-node/lib/services/bitcoind.js:1686:30
Mar  9 17:27:54 token-node-litecoin litecoin[24684]: at newCallback (/mnt/litecoin/node/node_modules/litecore-node/node_modules/litecoind-rpc/lib/index.js:52:16)

[litecoin.service.txt](https://github.com/litecoin-project/litecore-node/files/1797830/litecoin.service.txt)

```
my vps setup:
```
apt-get install libzmq3-dev build-essential sudo mc htop curl git -y
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
apt-get install -y nodejs
node -v
npm -v
useradd -s /bin/bash -mG sudo litecoin
passwd litecoin
mkdir -p /mnt/litecoin
chmod 777 /mnt/litecoin
chmod 777 /usr/bin
chmod 777 /usr/lib/node_modules
su litecoin
cd ~
pwd
npm install -g litecore-node
which litecore-node
litecore-node
litecore-node create /mnt/litecoin/node
cd /mnt/litecoin/node
litecore-node install insight-api
litecore-node install insight-ui
#Edit datadir in litecore-node
cd /mnt/litecoin/node/data
wget http://bootstrap.litecoinnode.org/bootstrap.dat
#/etc/rsyslog.d/litecoin.conf
service rsyslog restart
litecore-node start
chown -R litecoin.litecoin /mnt/litecoin
#/usr/lib/systemd/system/litecored.service
systemctl enable litecoin
systemctl start litecoin
reboot

```

**Comment by minzak** [comment]
At last. error was in insight-api.

**Comment by upklio** [comment]
What was the error, how did you fix it?
